version: '3.9'

services:

  db:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    hostname: mongo
    ports:
      - 27018:27017
    networks:
      - fastapi-network
    volumes:
      - mongodb_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  cache:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6380
    networks:
      - fastapi-network

  fastapi:
    image: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi
    hostname: fastapi
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 80"]
    ports:
      - 8000:80
      - 5678:5678
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      ACCESS_TOKEN_ALGORITHM: ${ACCESS_TOKEN_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - $PWD/app:/usr/src/app
    networks:
      - fastapi-network
    links:
      - db
      - cache

volumes:
  mongodb_vol:

networks:
  fastapi-network: